### ISSUE TITLE
copy/paste into the terminal

### ISSUE THREAD

**Issue by jwcooper** [adafruit/Adafruit-WebIDE#25]

**Comment by coreyfro** [comment]
I hate zombie topics as much as the next guy, but this is a really sticky issue.

I was hoping to use the WebIDE for a class on IoT schtuff I'm doing for free in the SF Bay Area, especially since I don't want to have to help people contend with various OS's, but I don't know if I have a choice.

The terminal APP that is a part of the WebIDE does not seem to have a method of pasting that is cross platform.  I have tried both Windows 10 and Ubuntu, Firefox and Chrome, and I have not found a single way to paste to any of these options.

I do not have a Mac to work with, but I cannot depend on a single platform, I must support everybody.

May I suggest a simple paste link in the terminal bar?  I imagine it would be a macro that turns the paste buffer in to key-presses.  Probably not the friendliest solution.

I know it may not be the scope of the project to be a one stop shop for interfacing the pi, but with this, things would be so much less messy.

Thanks.

**Comment by jwcooper** [comment]
We're closing all existing issues as we have a fairly large update to the webide. Please create a new issue for any issues found once we release the new version. Thanks!
